# Generated by Django 3.1.6 on 2021-11-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CmComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_comment', models.CharField(max_length=100)),
                ('cm_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('com_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='community.category')),
            ],
        ),
    ]
