# Generated by Django 3.0.6 on 2021-08-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='post_attachment',
        ),
    ]
