# Generated by Django 3.2.9 on 2021-11-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20211104_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmcomment',
            name='cm_date',
            field=models.DateTimeField(null=True),
        ),
    ]
