# Generated by Django 3.2.9 on 2021-11-04 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_community_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='like',
        ),
        migrations.AddField(
            model_name='community',
            name='likes_user',
            field=models.ManyToManyField(blank=True, related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
